[project]
name = "pygrowthstandards"
version = "0.2.0"
description = "A Python library for calculating child growth z-scores and percentiles using WHO and INTERGROWTH-21st standards"
readme = "README.md"
requires-python = ">=3.11"
license = { text = "MIT" }
authors = [{ name = "Yannngn", email = "contato.yannnob@gmail.com" }]
maintainers = [{ name = "Yannngn", email = "contato.yannnob@gmail.com" }]
keywords = [
    "growth",
    "pediatrics",
    "who",
    "intergrowth",
    "z-score",
    "percentile",
    "anthropometry",
    "children",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Healthcare Industry",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
    "Topic :: Scientific/Engineering :: Information Analysis",
]
dependencies = ["pandas[computation, parquet, plot]>=2.1.0,<3.0.0"]

[project.urls]
Homepage = "https://github.com/Yannngn/pygrowthstandards"
Repository = "https://github.com/Yannngn/pygrowthstandards"
Issues = "https://github.com/Yannngn/pygrowthstandards/issues"
Documentation = "https://github.com/Yannngn/pygrowthstandards#readme"

[dependency-groups]
dev = [
    { include-group = "tools" },
    { include-group = "test" },
    { include-group = "build" },
    "setuptools>=82.0.0",
]

optional = [
    { include-group = "excel" },
    { include-group = "pdf" },
    { include-group = "performance" },
]

excel = ["pandas[excel]>=2.1.0,<3.0.0"]
pdf = ["docling>=2.42.2"]

tools = ["ruff", "ty", "pydocstyle"]
test = ["pytest", "pytest-benchmark"]
build = ["build>=1.3.0", "twine>=6.1.0"]

performance = ["pandas[performance, computation]>=2.1.0,<3.0.0"]

docs = [
    "furo>=2025.12.19",
    "sphinx>=9.0.4",
    "sphinx-autodoc-typehints>=3.6.1",
    "sphinx-rtd-theme>=3.1.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
addopts = "-m 'not performance'"
markers = [
    "performance: mark tests as performance/benchmark (skipped by default)",
]

[tool.pydocstyle]
convention = "google"
match-dir = "src"
add-ignore = [
    "D100",
    "D103",
    "D104",
    "D200",
    "D212",
] # Ignore missing module, function, package doc errors

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/pygrowthstandards"]

[tool.hatch.build.targets.wheel.sources]
"src" = ""

[tool.hatch.build.targets.sdist]
include = [
    "/src",
    "/tests",
    "/data/pygrowthstandards_*.parquet",
    "/README.md",
    "/LICENSE",
    "/pyproject.toml",
    "/CHANGELOG.md",
    "/CONTRIBUTING.md",
]

[tool.ruff]
line-length = 144
target-version = "py311"

[tool.ty]
# Configure source directories
src.include = ["src", "scripts"]
