[project]
name = "pygrowthstandards"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "scipy>=1.15.3",
    "pandas>=2.3.0",
    "pyarrow>=21.0.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "pytest>=8.4.1",
]

tests = ["pytest>=8.4.0"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
