[project]
name = "pygrowthstandards"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "scipy>=1.15.3",
    "pandas>=2.3.0",
]

[dependency-groups]
dev = [
    "docling>=2.36.1",
    "openpyxl>=3.1.5",
    "pypdfium2>=4.30.1",
]
tests = [
    "pytest>=8.4.0",
]

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
pythonpath = [
    "src",
]
