[project]
name = "pygrowthstandards"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "scipy>=1.15.3",
    "pandas>=2.3.0",
    "pyarrow>=21.0.0",
]

[dependency-groups]
dev = ["openpyxl>=3.1.5", "pre-commit>=4.2.0", "pytest>=8.4.1"]
pdf = ["docling>=2.42.2"]

tests = ["pytest>=8.4.0"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
